name: Trigger Site Build

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger build on kaushalpartani.github.io
      env:
        GH_PAT: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_PAT" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/kaushalpartani/kaushalpartani.github.io/actions/workflows/dispatch.yml/dispatches \
          -d '{"ref":"main"}'

