name: Trigger Workflows in kaushalpartani.github.io

on:
  push:
    branches:
      - main

jobs:
  trigger_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ci.yaml workflow
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GH_ACCESS_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/kaushalpartani/kaushalpartani.github.io/actions/workflows/ci.yaml/dispatches \
            -d '{"ref": "v4"}'
          
  trigger_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy.yml workflow
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GH_ACCESS_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/kaushalpartani/kaushalpartani.github.io/actions/workflows/deploy.yml/dispatches \
            -d '{"ref": "v4"}'

